### ISSUE TITLE
Make docker-compose more robust

### ISSUE THREAD

**Issue by tobiasKaminsky** [AlvaroBrey/nextcloud-client-testing-server#1]
In order to have this for a very long time, we should make base docker image more robust.
```
 nextcloud-ephemeral-stable24:
    build:
      context: .
      args:
        BRANCH: stable24
    ports:
      - "80:80"

```

is based on FROM ghcr.io/nextcloud/continuous-integration-shallow-server:latest

this will in ~1-2 no longer work.

Same is, when we want to use this as a base for stable16-23.

Therefore I suggest that we 
- use :latest tag only on master
- on any other stable16-24 we rely on a server tag
